"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var transform_1 = require("./transform");
exports.transform = transform_1.default;
var clone_1 = require("./clone");
exports.clone = clone_1.default;
var isEqual_1 = require("./isEqual");
exports.isEqual = isEqual_1.default;
var trueIfAbsent_1 = require("./trueIfAbsent");
exports.trueIfAbsent = trueIfAbsent_1.default;
var bind_1 = require("./bind");
exports.bind = bind_1.default;
var getDefaultOfType_1 = require("./getDefaultOfType");
exports.getDefaultOfType = getDefaultOfType_1.default;
var shallowCopy_1 = require("./shallowCopy");
exports.shallowCopy = shallowCopy_1.default;
var checkType_1 = require("./checkType");
exports.isString = checkType_1.isString;
exports.isBoolean = checkType_1.isBoolean;
exports.isDate = checkType_1.isDate;
exports.isNumber = checkType_1.isNumber;
exports.isNull = checkType_1.isNull;
exports.isUndefined = checkType_1.isUndefined;
exports.isObject = checkType_1.isObject;
exports.isNullOrUndefined = checkType_1.isNullOrUndefined;
//# sourceMappingURL=index.js.map